"""
msg_to_markdown.py — Part of the AutoRAID pipeline.
Converts Outlook .msg files into Markdown notes.

Windows equivalent of eml_to_markdown.py. Accepts the .msg format that
Outlook for Windows produces when you drag messages to a folder.

Produces identical output structure to eml_to_markdown.py so the same
RAID log prompt and downstream tooling works unchanged.

Requirements:
    pip install extract-msg markdownify
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
try:
    import extract_msg
    HAS_EXTRACT_MSG = True
except ImportError:
    HAS_EXTRACT_MSG = False

try:
    from markdownify import markdownify as md_convert
    HAS_MARKDOWNIFY = True
except ImportError:
    HAS_MARKDOWNIFY = False

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Map sender-domain (or full address) fragments → project tag.
# Keys are matched case-insensitively as substrings against the From header.
# First match wins.
SENDER_PROJECT_RULES: dict[str, str] = {
    "hhglobal.com":   "HHG",
    "inwk.com":       "HHG",
    "westmonroe.com": "WM",
    # Add more as needed:
    # "clientdomain.com": "ClientProject",
}

# Default tags applied to every generated note
DEFAULT_TAGS = ["email", "inbox"]

# Name of the index file that tracks processed Message-IDs
INDEX_FILENAME = ".ingest-index.json"

# Name of the vault-internal log file written inside md_dir
LOG_FILENAME = "ingest-log.md"

# ---------------------------------------------------------------------------
# Helpers (shared with eml_to_markdown.py)
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    text = re.sub(r"[^\w\s-]", "", text).strip()
    text = re.sub(r"\s+", " ", text)
    return text[:120] or "untitled-email"


def load_index(md_dir: Path) -> dict[str, str]:
    index_path = md_dir / INDEX_FILENAME
    if index_path.exists():
        try:
            return json.loads(index_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_index(md_dir: Path, index: dict[str, str]) -> None:
    (md_dir / INDEX_FILENAME).write_text(
        json.dumps(index, indent=2), encoding="utf-8"
    )


def resolve_project(sender: str) -> str:
    sender_lower = sender.lower()
    for fragment, project in SENDER_PROJECT_RULES.items():
        if fragment.lower() in sender_lower:
            return project
    return ""


def html_to_markdown(html: str) -> str:
    if HAS_MARKDOWNIFY:
        return md_convert(
            html,
            heading_style="ATX",
            bullets="-",
            strip=["script", "style", "head"],
        ).strip()
    text = re.sub(r"<[^>]+>", " ", html)
    for entity, replacement in [
        ("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"),
        ("&gt;", ">"), ("&quot;", '"'),
    ]:
        text = text.replace(entity, replacement)
    return text.strip()


def cleanup_body(body: str) -> str:
    body = body.replace("\r\n", "\n").replace("\r", "\n")
    body = re.sub(r"\nSent from my .*$", "", body,
                  flags=re.IGNORECASE | re.MULTILINE)
    body = re.sub(r"\nGet Outlook for .*$", "", body,
                  flags=re.IGNORECASE | re.MULTILINE)

    markers = [
        r"^On .{10,100} wrote:\s*$",
        r"^From:\s.+$",
        r"^Sent:\s.+$",
        r"^-----Original Message-----\s*$",
        r"^_{5,}\s*$",
    ]
    lines = body.split("\n")
    out: list[str] = []
    for line in lines:
        if any(re.match(p, line.strip(), re.IGNORECASE) for p in markers):
            break
        out.append(line)

    body = "\n".join(out).strip()
    return re.sub(r"\n{3,}", "\n\n", body)


def append_vault_log(md_dir: Path, message: str) -> None:
    log_path = md_dir / LOG_FILENAME
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry = f"- `{timestamp}` {message}\n"
    if not log_path.exists():
        log_path.write_text(
            "# Email Ingest Log\n\nThis file is auto-generated by msg_to_markdown.py.\n\n",
            encoding="utf-8",
        )
    with log_path.open("a", encoding="utf-8") as f:
        f.write(entry)


# ---------------------------------------------------------------------------
# Core converter
# ---------------------------------------------------------------------------

def convert_one(
    msg_path: Path,
    md_dir: Path,
    attachment_base_dir: Path,
    index: dict[str, str],
) -> tuple[Path | None, str]:
    """
    Convert a single .msg file to a Markdown note.

    Returns (md_path, status) where status is one of:
      "created"  - new note written
      "skipped"  - already in index (duplicate)
      "error"    - exception occurred
    """
    if not HAS_EXTRACT_MSG:
        return None, "error: extract-msg not installed. Run: pip install extract-msg"

    try:
        msg = extract_msg.openMsg(str(msg_path))
    except Exception as exc:
        return None, f"error reading {msg_path.name}: {exc}"

    try:
        # --- Deduplication via Message-ID ---
        message_id = (msg.messageId or "").strip()
        if not message_id:
            message_id = f"synthetic:{msg_path.stem}"

        if message_id in index:
            return None, f"skipped (duplicate) {msg_path.name}"

        # --- Extract headers ---
        subject = (msg.subject or "").strip()
        sender  = (msg.sender or "").strip()
        to      = (msg.to or "").strip()
        date    = str(msg.date) if msg.date else ""

        # --- Resolve output path ---
        slug    = slugify(subject or msg_path.stem)
        md_path = md_dir / f"{slug}.md"
        counter = 1
        base_slug = slug
        while md_path.exists():
            md_path = md_dir / f"{base_slug}-{counter}.md"
            counter += 1

        # --- Extract body ---
        body = ""
        if msg.body:
            body = cleanup_body(msg.body)
        elif msg.htmlBody:
            raw_html = msg.htmlBody
            if isinstance(raw_html, bytes):
                raw_html = raw_html.decode("utf-8", errors="replace")
            body = cleanup_body(html_to_markdown(raw_html))

        # --- Extract attachments ---
        attachment_dir = attachment_base_dir / slug
        saved_attachments: list[str] = []

        if msg.attachments:
            attachment_dir.mkdir(parents=True, exist_ok=True)
            for att in msg.attachments:
                att_name = getattr(att, "longFilename", None) or \
                           getattr(att, "shortFilename", None) or "attachment"
                safe_name = re.sub(r"[^\w.\- ]", "_", att_name).strip() or "attachment"
                dest = attachment_dir / safe_name
                c = 1
                stem, suffix = Path(safe_name).stem, Path(safe_name).suffix
                while dest.exists():
                    dest = attachment_dir / f"{stem}_{c}{suffix}"
                    c += 1
                try:
                    data = att.data
                    if data:
                        dest.write_bytes(data)
                        saved_attachments.append(dest.name)
                except Exception:
                    continue

        # --- Build tags and project ---
        project = resolve_project(sender)
        tags = DEFAULT_TAGS.copy()
        if project:
            tags.append(project.lower().replace(" ", "-"))

        # --- Render YAML frontmatter ---
        def q(s: str) -> str:
            return s.replace('"', '\\"')

        tags_yaml = ", ".join(f'"{t}"' for t in tags)
        attachment_links = ""
        if saved_attachments:
            link_lines = "\n".join(f'  - "[[{a}]]"' for a in saved_attachments)
            attachment_links = f"attachments:\n{link_lines}\n"

        frontmatter = (
            f"---\n"
            f'type: email\n'
            f'subject: "{q(subject)}"\n'
            f'from: "{q(sender)}"\n'
            f'to: "{q(to)}"\n'
            f'date: "{q(date)}"\n'
            f'message_id: "{q(message_id)}"\n'
            f'project: "{q(project)}"\n'
            f'tags: [{tags_yaml}]\n'
            f'source: "[[{msg_path.name}]]"\n'
            f"{attachment_links}"
            f"---\n"
            f"\n"
            f"## Summary\n\n"
            f"## Key points\n\n"
            f"## Actions\n\n"
        )

        if saved_attachments:
            frontmatter += "## Attachments\n\n"
            for a in saved_attachments:
                frontmatter += f"- [[{a}]]\n"
            frontmatter += "\n"

        frontmatter += f"## Body\n\n{body}\n"

        md_path.write_text(frontmatter, encoding="utf-8")
        index[message_id] = md_path.name

        return md_path, "created"

    finally:
        try:
            msg.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) not in (3, 4):
        print("Usage: python msg_to_markdown.py <msg_dir> <md_dir> [<attachment_dir>]")
        print()
        print("  msg_dir        : folder containing .msg source files")
        print("  md_dir         : folder where Markdown notes are written")
        print("  attachment_dir : folder for extracted attachments")
        print("                   (defaults to <md_dir>\\..\\Attachments)")
        sys.exit(1)

    msg_dir  = Path(sys.argv[1]).expanduser().resolve()
    md_dir   = Path(sys.argv[2]).expanduser().resolve()
    attachment_base = (
        Path(sys.argv[3]).expanduser().resolve()
        if len(sys.argv) == 4
        else md_dir.parent / "Attachments"
    )

    md_dir.mkdir(parents=True, exist_ok=True)
    attachment_base.mkdir(parents=True, exist_ok=True)

    index = load_index(md_dir)
    created_count = skipped_count = error_count = 0

    for msg_path in sorted(msg_dir.glob("*.msg")):
        result_path, status = convert_one(msg_path, md_dir, attachment_base, index)
        if status.startswith("created"):
            created_count += 1
            print(f"[created]  {result_path.name}")
            append_vault_log(md_dir, f"Created `{result_path.name}` from `{msg_path.name}`")
        elif status.startswith("skipped"):
            skipped_count += 1
            print(f"[skipped]  {msg_path.name}")
        else:
            error_count += 1
            print(f"[error]    {status}", file=sys.stderr)
            append_vault_log(md_dir, f"ERROR: {status}")

    save_index(md_dir, index)
    print(f"\nDone. created={created_count}  skipped={skipped_count}  errors={error_count}")


if __name__ == "__main__":
    main()
